### ISSUE TITLE
Disable autoComplete on the Search field(input field) or make it controllable

### ISSUE THREAD

**Issue by OmegaHawkeye** [albingroen/react-cmdk#16]
Hello,

I genuinely dislike autoComplete features in annoying places. Therefore I would ask if u could make it permanently off or atleast programmable via props. The only place I noticed it was in the Search field(input field).

I can also look into it and mby make a pull request.

Thx for this component/library👍🏼

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/albingroen/react-cmdk/issues/16">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/albingroen/react-cmdk/issues/16/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/albingroen/react-cmdk/issues/16/pledge.svg">
</picture>
</a>

**Comment by albingroen** [comment]
May I ask why this is a problem?

**Comment by marek-hanzal** [comment]
Hello - I've got the same problem: it would be nice to have it controllable, because when the autocomplete pop's up, arrow keys are consumed by browser's autocomplete instead of jumping in the list; this breaks the whole usability of command component: (its czech, but the idea is there)
![image](https://user-images.githubusercontent.com/13855126/218344258-cfd1b3ad-a709-4ada-95e1-c35284fb7a67.png)

Because autocomplete is not possible turn off by any simple way (like using CSS or so), thus a flag would be reaaaaaly nice.

At least: you can give control to your users, not force them to use your opinion.

**Comment by danopia** [comment]
Was this actually completed? I don't see a way of disabling the autocomplete on the textbox in v1.3.9.

The autocomplete UI steals arrow key presses, breaking the flow of navigating down to the 2nd, 3rd, etc match in the palette.
One must first break out of autocomplete with Escape and then arrow down to the 2nd match.
